cmake_minimum_required(VERSION 3.22.1)
project(aether3d_core LANGUAGES CXX)
set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)
add_library(aether3d_core SHARED native-lib.cpp)
target_compile_options(aether3d_core PRIVATE -Wall -Wextra -Wpedantic -O3 -ffunction-sections -fdata-sections)
target_link_options(aether3d_core PRIVATE -Wl,--gc-sections -Wl,--exclude-libs,ALL)
find_library(log-lib log)
target_link_libraries(aether3d_core PRIVATE ${log-lib})
